// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLNetExampleML.Model
{
    public class ModelInput
    {
        [ColumnName("word"), LoadColumn(0)]
        public string Word { get; set; }


        [ColumnName("isPositive"), LoadColumn(1)]
        public bool IsPositive { get; set; }


        [ColumnName("isNegative"), LoadColumn(2)]
        public float IsNegative { get; set; }


    }
}
